name: github actions pratice

on: [ push,pull_request ]

jobs:
  this-is-test-job:  
    runs-on: ubuntu-latest
    steps:
      - name: this is printing funtion
        run: echo "hellow world"
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python    

  second-job:
    runs-on: windows-latest
    needs: ["this-is-test-job"]
    steps:
      - name: current directory
        run: Get-Location