
name: Actions workflow

on:
  repository_dispatch:

       

jobs:
  using-third-party-actions:
    runs-on: ubuntu-latest
    steps:
      - name: using ready made github actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: venkat bro
      - name: priting output
        run: echo "${{steps.greet.outputs.time}}"    
