name:  praticing the github actions

on: [push]

jobs:
    job-name:
        runs-on: ubuntu-latest
        steps:
            - name: printing the string
              run: echo "hellow world github"
            - name: multiline script
              run: |
               node -v
               ls
        
            

